# Loading Data
Now that we are more familiar with the NumPy and Pandas packages, we can start loading data into Python to start working with. We can load data into our notebook a few different ways. Four different ways that we'll look at in this notebook are:
1. Generating data within our notebook using `np.arange()`
2. Generating data within our notebook using `np.random` functions
3. Importing external data into our notebook using Pandas DataReader
4. Importing an external .csv file into our notebook

## Generating Data with NumPy arange

In the last chapter, we demonstrated how to create numpy arrays by providing all the values in an array. Numpy also allows us to more efficiently generate a range of values. Let's first look at the `arange()` function that creates a range of intervals. The value 30 that we put inside the parentheses is the ending interval of the array. This means that Array_3 will start at 0, and end before 30.

In [1]:
import numpy as np
Array_1 = np.arange(30)
Array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

We can also provide a starting interval, in this case 3, and an ending interval, in this case 7. This array starts at 3 and ends before 7.

In [2]:
Array_2 = np.arange(3,7)
Array_2

array([3, 4, 5, 6])

Another information we can add is a step. For example, let's create an array starting at 1, ending at 10, and the 2 step means the range runs every other number. And again, it goes up to but not the last value.

In [4]:
# Arrange (starting interval, ending interval, step)
Array_3 = np.arange(1, 10, 2)
Array_3

array([1, 3, 5, 7, 9])

The last two examples are arrays consists of a range of integers. We can also gather a range of float values within an interval. For this purpose we'll use the `linspace()` function. This function includes a starting value, an ending value, and the number of items in this array. This example will return 20 values evenly spaced between 0 to 5.

In [6]:
# Gathering a range of values within an interval can also be done.
Arrry_4 = np.linspace(00, 5, 20)
Arrry_4

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

A range has similar properties as lists and other numpy arrays when it comes to indexing. Let's use Array_3 that we created earlier as an example. To call the 5th value within the array, we call index 4 in the square brackes.

In [7]:
Arrry_4[4]

np.float64(1.0526315789473684)

## Generating Data with NumPy random

There are a lot of functions that allow us to generate randomized values in a numpy array. Let start with `random.rand` function. It generates random floats from 0 to 1. In the parentheses we can put how many numbers we want to generate. In this example we generated 10 random floats.

In [8]:
# creating an array of random floats
np.random.rand(10)

array([0.17732931, 0.35425589, 0.28517093, 0.55170374, 0.94084929,
       0.01452726, 0.33367214, 0.71463017, 0.15171722, 0.73178648])

Another function we can use is the `random.randint` function. It can be used to gather a random integer within a range. For example, we will have a random whole number between 10 and 20. It is important to note that this function includes 10 up to 19.

In [10]:
# gathering a random interger within a range
np.random.randint(10,20)

13

If we add a number in the end, we can generate a number of random integers wthin this range. This example creates an array of 5 integers in between 10 and 20. We might get repeatative values from the random functions.

In [11]:
# gathering an array of random intergers within a range
np.random.randint(10,20,5)

array([19, 15, 19, 11, 11], dtype=int32)

We can also create a random matrix by providing a shape. For example, let's create an array of integers in between 1 and 100, the matrix contains 2 rows and 4 columns. 

In [12]:
np.random.randint(1,100, (2,4))

array([[97, 17, 37, 27],
       [67, 13, 26, 35]], dtype=int32)

Since all the numbers are randomly generated, if we run all of these functions again we're likely to get completely different values. If we want to generate a random number and keep it throughout a model, we can use the seed function.

Seed function tells Python under the hood to "randomize" from the same method for any computer.  So, it basically eliminates randomness.  We would do this to ensure reproducibiliy.  But in production, randomization helps in forecasting, so you could disable seed there.

In [14]:
# fixing the randomizer to get the same random values for reproduction
np.random.seed(100)
np.random.rand(3)

array([0.54340494, 0.27836939, 0.42451759])

If we remove the seed line, we'll get 3 different values every time we run the code.

In [15]:
# without the seed
np.random.rand(3)

array([0.84477613, 0.00471886, 0.12156912])

If we run the same code again, adding back the seed, we get the same result.

In [16]:
np.random.seed(100)
np.random.rand(3)

array([0.54340494, 0.27836939, 0.42451759])

## Importing External Data with Pandas DataReader

Rather than defining our data manually, we can leverage functionality within Pandas to connect to and import external data into our notebook.

Functions from `pandas_datareader.data` extract external data from the web into a Pandas DataFrame. We'll look at an example of using datareader to import financial data from Naver.

In [10]:
%pip install pandas-datareader

Note: you may need to restart the kernel to use updated packages.


In [5]:
%pip install finance-datareader

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.9 MB 9.7 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 17.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 13.7 MB/s  0:00:00

   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ----------------------------

In [9]:
import yfinance as yf

# Samsung electronics (005930) on the KRX
# Note: yfinance usually requires the suffix .KS for KOSPI
df = yf.download('005930.KS', start='2022-01-01', end='2022-01-31')

print(df.head())

[*********************100%***********************]  1 of 1 completed

Price              Close          High           Low          Open    Volume
Ticker         005930.KS     005930.KS     005930.KS     005930.KS 005930.KS
Date                                                                        
2022-01-04  72089.250000  72547.250318  71722.849746  72180.850064  12427416
2022-01-05  70898.437500  72364.038275  69982.437016  72180.838178  25470640
2022-01-06  70440.445312  71081.645725  70165.645136  70257.245195  12931954
2022-01-07  71722.835938  71814.435983  70898.435524  71539.635846  15163757
2022-01-10  71448.039062  71539.639113  70623.638612  71539.639113   9947422


In [10]:
# Import yfinance for yahoo data
import yfinance as yf

stock = 'SPY'
startdate = '2022-01-01'
enddate = '2022-01-31'

stocks_df = yf.download(stock, start=startdate,end=enddate)

print(stocks_df)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date                                                                 
2022-01-03  450.644379  450.776461  447.003088  449.314262   72668200
2022-01-04  450.493500  452.785845  448.635113  452.068895   71178700
2022-01-05  441.843048  450.899148  441.748708  450.125599  104538900
2022-01-06  441.427948  444.144781  439.060148  441.380792   86858900
2022-01-07  439.682800  442.616612  438.324384  441.437434   85111600
2022-01-10  439.135651  439.352601  430.730460  436.484859  119362000
2022-01-11  443.135498  443.229838  435.871743  438.871597   74303100
2022-01-12  444.333496  446.390006  442.371355  444.871209   67605400
2022-01-13  438.211212  446.088134  437.182972  445.437224   91173100
2022-01-14  438.390411  438.739444  433.843491  435.060411   95890900
2022-01-18  430.626678  433.900080  429.513541  433.692544  109709100
2022-01-19  426.1552

We can use functions from the `yfinance` package to connect to yahoo finance data for a particular stock, in this case an ETF that tracks the S&P 500 stock market index. This time we can define our arguments outside of the function. This will make them easier to find and change in the future. We can also store the resulting DataFrame for future use in our notebook.

In [ ]:
# Import yfinance for yahoo data


[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date                                                                 
2022-01-03  450.644379  450.776461  447.003088  449.314262   72668200
2022-01-04  450.493500  452.785845  448.635113  452.068895   71178700
2022-01-05  441.843048  450.899148  441.748708  450.125599  104538900
2022-01-06  441.427948  444.144781  439.060148  441.380792   86858900
2022-01-07  439.682800  442.616612  438.324384  441.437434   85111600
2022-01-10  439.135651  439.352601  430.730460  436.484859  119362000
2022-01-11  443.135498  443.229838  435.871743  438.871597   74303100
2022-01-12  444.333496  446.390006  442.371355  444.871209   67605400
2022-01-13  438.211212  446.088134  437.182972  445.437224   91173100
2022-01-14  438.390411  438.739444  433.843491  435.060411   95890900
2022-01-18  430.626678  433.900080  429.513541  433.692544  109709100
2022-01-19  426.1552

## Importing External .csv

One of the more powerful ways of creating a DataFrame is to import a .csv file. This will save tremendous amount of time in recreating a data source in Python and allow Python to read the data in. We can use the `pd.read.csv()` function to do this.

When using this function, either the relative file path or the complete file path must be submitted between quotation marks. For a relative file path, if the csv. file is in the same working directory folder as the notebook, you can simply submit the file name with the csv. suffix. 

If the file is in another folder, then you must provide extra information of the path pandas should take to refer to the file (ie. 'datafolder/Data Source.csv').

In [11]:
#Importing an external .csv using a relative file path
#Importing an external .csv using a relative file path
dataframe_3 = pd.read_csv('Data Source.csv')

dataframe_3

,Store,Date,CategoryID,ProductID,Q1,Q2,Q3,Q4
0,1,3/10/2019 0:00:00,1,11XXRP-P,24924.50,46039.49,41595.55,NaN
1,1,6/4/2019 0:00:00,2,12XXRP-Q,50605.27,44682.74,47928.89,NaN
2,1,1/16/2019 0:00:00,3,13XXRP,13740.12,10887.84,11523.47,NaN
3,1,10/18/2019 0:00:00,4,14XXRP,39954.04,d35351.21,36826.95,NaN
4,1,4/11/2019 0:00:00,5,15XXRP-A,32229.38,29620.81,26468.27,NaN
...,...,...,...,...,...,...,...,...
1882,40,3/24/2019 0:00:00,44,4044XXRP,3280.00,3556.22,2965.33,3041.41
1883,40,3/24/2019 0:00:00,44,4044XXRP,3280.00,3556.22,2965.33,3041.41
1884,40,3/24/2019 0:00:00,44,4044XXRP,3280.00,3556.22,2965.33,3041.41
1885,40,9/30/2019 0:00:00,49,4049XXRP,0.00,NaN,NaN,-23.99


We will continue to work with .csv data in Python in the next section of this chapter. However, much like what we see in a real-world setting, data is not always perfect. We can see that we have errors in our data, such as NaN values and duplicates.